export const MONTHS = {
  '01': 'January',
  '02': 'February',
  '03': 'March',
  '04': 'April',
  '05': 'May',
  '06': 'June',
  '07': 'July',
  '08': 'August',
  '09': 'September',
  10: 'October',
  11: 'November',
  12: 'December'
}
export const DAY = {
  0: 'Sunday',
  1: 'Monday',
  2: 'Tuesday',
  3: 'Wednesday',
  4: 'Thursday',
  5: 'Friday',
  6: 'Saturday'
}
export const OPTIONS = {
  method: 'GET',
  headers: {
    'X-RapidAPI-Host': 'weatherapi-com.p.rapidapi.com',
    'X-RapidAPI-Key': '2c9def7ff9msh9694b4a32b1be6cp146ff6jsnd33a36f39afd'
  }
}
export const COUNTRIES_AND_CITIES = [
  "Afghanistan",
  "Kabul, Afghanistan",
  "Albania",
  "Tirana, Albania",
  "Algeria",
  "Algiers, Algeria",
  "Andorra",
  "Andorra la Vella, Andorra",
  "Angola",
  "Luanda, Angola",
  "Antigua and Barbuda",
  "Saint John's, Antigua and Barbuda",
  "Argentina",
  "Buenos Aires, Argentina",
  "Armenia",
  "Yerevan, Armenia",
  "Australia",
  "Canberra, Australia",
  "Sydney, Australia",
  "Melbourne, Australia",
  "Austria",
  "Vienna, Austria",
  "Azerbaijan",
  "Baku, Azerbaijan",
  "Bahamas",
  "Nassau, Bahamas",
  "Bahrain",
  "Manama, Bahrain",
  "Bangladesh",
  "Dhaka, Bangladesh",
  "Barbados",
  "Bridgetown, Barbados",
  "Belarus",
  "Minsk, Belarus",
  "Belgium",
  "Brussels, Belgium",
  "Belize",
  "Belmopan, Belize",
  "Benin",
  "Porto-Novo, Benin",
  "Bhutan",
  "Thimphu, Bhutan",
  "Bolivia",
  "La Paz, Bolivia",
  "Sucre, Bolivia",
  "Bosnia and Herzegovina",
  "Sarajevo, Bosnia and Herzegovina",
  "Botswana",
  "Gaborone, Botswana",
  "Brazil",
  "Brasilia, Brazil",
  "São Paulo, Brazil",
  "Rio de Janeiro, Brazil",
  "Brunei",
  "Bandar Seri Begawan, Brunei",
  "Bulgaria",
  "Sofia, Bulgaria",
  "Burkina Faso",
  "Ouagadougou, Burkina Faso",
  "Burundi",
  "Gitega, Burundi",
  "Cabo Verde",
  "Praia, Cabo Verde",
  "Cambodia",
  "Phnom Penh, Cambodia",
  "Cameroon",
  "Yaounde, Cameroon",
  "Canada",
  "Ottawa, Canada",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Central African Republic",
  "Bangui, Central African Republic",
  "Chad",
  "N'Djamena, Chad",
  "Chile",
  "Santiago, Chile",
  "China",
  "Beijing, China",
  "Shanghai, China",
  "Chongqing, China",
  "Colombia",
  "Bogota, Colombia",
  "Medellin, Colombia",
  "Comoros",
  "Moroni, Comoros",
  "Congo, Democratic Republic of the",
  "Kinshasa, Congo, Democratic Republic of the",
  "Congo, Republic of the",
  "Brazzaville, Congo, Republic of the",
  "Costa Rica",
  "San Jose, Costa Rica",
  "Croatia",
  "Zagreb, Croatia",
  "Cuba",
  "Havana, Cuba",
  "Cyprus",
  "Nicosia, Cyprus",
  "Czech Republic",
  "Prague, Czech Republic",
  "Denmark",
  "Copenhagen, Denmark",
  "Djibouti",
  "Djibouti, Djibouti",
  "Dominica",
  "Roseau, Dominica",
  "Dominican Republic",
  "Santo Domingo, Dominican Republic",
  "Ecuador",
  "Quito, Ecuador",
  "Guayaquil, Ecuador",
  "Egypt",
  "Cairo, Egypt",
  "El Salvador",
  "San Salvador, El Salvador",
  "Equatorial Guinea",
  "Malabo, Equatorial Guinea",
  "Eritrea",
  "Asmara, Eritrea",
  "Estonia",
  "Tallinn, Estonia",
  "Eswatini",
  "Mbabane, Eswatini",
  "Ethiopia",
  "Addis Ababa, Ethiopia",
  "Fiji",
  "Suva, Fiji",
  "Finland",
  "Helsinki, Finland",
  "France",
  "Paris, France",
  "Marseille, France",
  "Lyon, France",
  "Gabon",
  "Libreville, Gabon",
  "Gambia",
  "Banjul, Gambia",
  "Georgia",
  "Tbilisi, Georgia",
  "Germany",
  "Berlin, Germany",
  "Munich, Germany",
  "Frankfurt, Germany",
  "Ghana",
  "Accra, Ghana",
  "Greece",
  "Athens, Greece",
  "Grenada",
  "Saint George's, Grenada",
  "Guatemala",
  "Guatemala City, Guatemala",
  "Guinea",
  "Conakry, Guinea",
  "Guinea-Bissau",
  "Bissau, Guinea-Bissau",
  "Guyana",
  "Georgetown, Guyana",
  "Haiti",
  "Port-au-Prince, Haiti",
  "Honduras",
  "Tegucigalpa, Honduras",
  "Hungary",
  "Budapest, Hungary",
  "Iceland",
  "Reykjavik, Iceland",
  "India",
  "New Delhi, India",
  "Mumbai, India",
  "Bangalore, India",
  "Indonesia",
  "Jakarta, Indonesia",
  "Surabaya, Indonesia",
  "Iran",
  "Tehran, Iran",
  "Iraq",
  "Baghdad, Iraq",
  "Ireland",
  "Dublin, Ireland",
  "Israel",
  "Jerusalem, Israel",
  "Tel Aviv, Israel",
  "Italy",
  "Rome, Italy",
  "Milan, Italy",
  "Jamaica",
  "Kingston, Jamaica",
  "Japan",
  "Tokyo, Japan",
  "Osaka, Japan",
  "Jordan",
  "Amman, Jordan",
  "Kazakhstan",
  "Nur-Sultan, Kazakhstan",
  "Kenya",
  "Nairobi, Kenya",
  "Kiribati",
  "Tarawa, Kiribati",
  "Korea, North",
  "Pyongyang, Korea, North",
  "Korea, South",
  "Seoul, Korea, South",
  "Busan, Korea, South",
  "Kosovo",
  "Pristina, Kosovo",
  "Kuwait",
  "Kuwait City, Kuwait",
  "Kyrgyzstan",
  "Bishkek, Kyrgyzstan",
  "Laos",
  "Vientiane, Laos",
  "Latvia",
  "Riga, Latvia",
  "Lebanon",
  "Beirut, Lebanon",
  "Lesotho",
  "Maseru, Lesotho",
  "Liberia",
  "Monrovia, Liberia",
  "Libya",
  "Tripoli, Libya",
  "Liechtenstein",
  "Vaduz, Liechtenstein",
  "Lithuania",
  "Vilnius, Lithuania",
  "Luxembourg",
  "Luxembourg, Luxembourg",
  "Madagascar",
  "Antananarivo, Madagascar",
  "Malawi",
  "Lilongwe, Malawi",
  "Malaysia",
  "Kuala Lumpur, Malaysia",
  "Maldives",
  "Male, Maldives",
  "Mali",
  "Bamako, Mali",
  "Malta",
  "Valletta, Malta",
  "Marshall Islands",
  "Majuro, Marshall Islands",
  "Mauritania",
  "Nouakchott, Mauritania",
  "Mauritius",
  "Port Louis, Mauritius",
  "Mexico",
  "Mexico City, Mexico",
  "Guadalajara, Mexico",
  "Monterrey, Mexico",
  "Micronesia",
  "Palikir, Micronesia",
  "Moldova",
  "Chisinau, Moldova",
  "Monaco",
  "Monaco, Monaco",
  "Mongolia",
  "Ulaanbaatar, Mongolia",
  "Montenegro",
  "Podgorica, Montenegro",
  "Morocco",
  "Rabat, Morocco",
  "Casablanca, Morocco",
  "Mozambique",
  "Maputo, Mozambique",
  "Myanmar",
  "Naypyidaw, Myanmar",
  "Namibia",
  "Windhoek, Namibia",
  "Nauru",
  "Yaren District, Nauru",
  "Nepal",
  "Kathmandu, Nepal",
  "Netherlands",
  "Amsterdam, Netherlands",
  "Rotterdam, Netherlands",
  "New Zealand",
  "Wellington, New Zealand",
  "Auckland, New Zealand",
  "Nicaragua",
  "Managua, Nicaragua",
  "Niger",
  "Niamey, Niger",
  "Nigeria",
  "Abuja, Nigeria",
  "Lagos, Nigeria",
  "North Macedonia",
  "Skopje, North Macedonia",
  "Norway",
  "Oslo, Norway",
  "Oman",
  "Muscat, Oman",
  "Pakistan",
  "Islamabad, Pakistan",
  "Karachi, Pakistan",
  "Lahore, Pakistan",
  "Palau",
  "Ngerulmud, Palau",
  "Panama",
  "Panama City, Panama",
  "Papua New Guinea",
  "Port Moresby, Papua New Guinea",
  "Paraguay",
  "Asuncion, Paraguay",
  "Peru",
  "Lima, Peru",
  "Philippines",
  "Manila, Philippines",
  "Poland",
  "Warsaw, Poland",
  "Portugal",
  "Lisbon, Portugal",
  "Qatar",
  "Doha, Qatar",
  "Romania",
  "Bucharest, Romania",
  "Russia",
  "Moscow, Russia",
  "Saint Petersburg, Russia",
  "Rwanda",
  "Kigali, Rwanda",
  "Saint Kitts and Nevis",
  "Basseterre, Saint Kitts and Nevis",
  "Saint Lucia",
  "Castries, Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Kingstown, Saint Vincent and the Grenadines",
  "Samoa",
  "Apia, Samoa",
  "San Marino",
  "San Marino, San Marino",
  "Sao Tome and Principe",
  "Sao Tome, Sao Tome and Principe",
  "Saudi Arabia",
  "Riyadh, Saudi Arabia",
  "Jeddah, Saudi Arabia",
  "Senegal",
  "Dakar, Senegal",
  "Serbia",
  "Belgrade, Serbia",
  "Seychelles",
  "Victoria, Seychelles",
  "Sierra Leone",
  "Freetown, Sierra Leone",
  "Singapore",
  "Singapore, Singapore",
  "Slovakia",
  "Bratislava, Slovakia",
  "Slovenia",
  "Ljubljana, Slovenia",
  "Solomon Islands",
  "Honiara, Solomon Islands",
  "Somalia",
  "Mogadishu, Somalia",
  "South Africa",
  "Pretoria, South Africa",
  "Cape Town, South Africa",
  "Johannesburg, South Africa",
  "South Sudan",
  "Juba, South Sudan",
  "Spain",
  "Madrid, Spain",
  "Barcelona, Spain",
  "Sri Lanka",
  "Sri Jayawardenepura Kotte, Sri Lanka",
  "Colombo, Sri Lanka",
  "Sudan",
  "Khartoum, Sudan",
  "Suriname",
  "Paramaribo, Suriname",
  "Sweden",
  "Stockholm, Sweden",
  "Switzerland",
  "Bern, Switzerland",
  "Zurich, Switzerland",
  "Syria",
  "Damascus, Syria",
  "Taiwan",
  "Taipei, Taiwan",
  "Tajikistan",
  "Dushanbe, Tajikistan",
  "Tanzania",
  "Dodoma, Tanzania",
  "Dar es Salaam, Tanzania",
  "Thailand",
  "Bangkok, Thailand",
  "Timor-Leste",
  "Dili, Timor-Leste",
  "Togo",
  "Lome, Togo",
  "Tonga",
  "Nuku'alofa, Tonga",
  "Trinidad and Tobago",
  "Port of Spain, Trinidad and Tobago",
  "Tunisia",
  "Tunis, Tunisia",
  "Turkey",
  "Ankara, Turkey",
  "Istanbul, Turkey",
  "Turkmenistan",
  "Ashgabat, Turkmenistan",
  "Tuvalu",
  "Funafuti, Tuvalu",
  "Uganda",
  "Kampala, Uganda",
  "Ukraine",
  "Kyiv, Ukraine",
  "United Arab Emirates",
  "Abu Dhabi, United Arab Emirates",
  "Dubai, United Arab Emirates",
  "United Kingdom",
  "London, United Kingdom",
  "Manchester, United Kingdom",
  "Birmingham, United Kingdom",
  "United States",
  "Washington, D.C., United States",
  "New York, United States",
  "Los Angeles, United States",
  "Chicago, United States",
  "Uruguay",
  "Montevideo, Uruguay",
  "Uzbekistan",
  "Tashkent, Uzbekistan",
  "Vanuatu",
  "Port Vila, Vanuatu",
  "Vatican City",
  "Vatican City, Vatican City",
  "Venezuela",
  "Caracas, Venezuela",
  "Vietnam",
  "Hanoi, Vietnam",
  "Ho Chi Minh City, Vietnam",
  "Yemen",
  "Sanaa, Yemen",
  "Zambia",
  "Lusaka, Zambia",
  "Zimbabwe",
  "Harare, Zimbabwe"
]

export const WEATHER_CODES = {
  1000: ['Sunny', 'Moon'],
  1003: ['PartlyCloudy'],
  1009: ['Cloudy'],
  1030: ['Mist'],
  1006: ['Cloudy'],
  1063: ['RainCloud'],
  1066: ['Snow'],
  1069: ['IceSnow'],
  1072: ['IceSnow'],
  1087: ['CloudThunder'],
  1114: ['Snow'],
  1117: ['Snow'],
  1135: ['Mist'],
  1147: ['Mist'],
  1150: ['RainCloud'],
  1153: ['RainCloud'],
  1168: ['IceSnow'],
  1171: ['IceSnow'],
  1180: ['RainCloud'],
  1183: ['RainCloud'],
  1186: ['RainCloud'],
  1189: ['RainCloud'],
  1192: ['RainCloud'],
  1195: ['RainCloud'],
  1198: ['IceSnow'],
  1201: ['IceSnow'],
  1204: ['IceSnow'],
  1207: ['IceSnow'],
  1210: ['Snow'],
  1213: ['Snow'],
  1216: ['Snow'],
  1219: ['Snow'],
  1222: ['Snow'],
  1225: ['Snow'],
  1237: ['IceSnow'],
  1240: ['RainCloud'],
  1243: ['RainCloud'],
  1246: ['RainCloud'],
  1249: ['IceSnow'],
  1252: ['IceSnow'],
  1255: ['Snow'],
  1258: ['Snow'],
  1261: ['IceSnow'],
  1264: ['IceSnow'],
  1273: ['RainCloud'],
  1276: ['RainCloud'],
  1279: ['Snow'],
  1282: ['Snow']
}

export const DAY_MESSAGES = {
  1: "It's a rainy day. Take an umbrella.",
  2: "It's a cloudy day. Take a jacket.",
  3: "It's a sunny day. Take a hat.",
  4: "It's a windy day. Take a scarf.",
  5: "It's a snowy day. Take some warm clothes.",
  6: "It's a foggy day. Be careful."
}

export const LABELS = [
  '00:00',
  '01:00',
  '02:00',
  '03:00',
  '04:00',
  '05:00',
  '06:00',
  '07:00',
  '08:00',
  '09:00',
  '10:00',
  '11:00',
  '12:00',
  '13:00',
  '14:00',
  '15:00',
  '16:00',
  '17:00',
  '18:00',
  '19:00',
  '20:00',
  '21:00',
  '22:00',
  '23:00'
]
export const geolocationOptions = {
  enableHighAccuracy: false,
  timeout: 1000 * 60 * 1, // 1 min (1000 ms * 60 sec * 1 minute = 60 000ms)
  maximumAge: 1000 * 3600 * 24 // 24 hour
}
export const DEFAULT_LOCATIONS = [
  { latitude: 40.7128, longitude: -74.006 },
  { latitude: 51.5074, longitude: -0.1278 },
  { latitude: 48.8566, longitude: 2.3522 },
  { latitude: 35.6895, longitude: 139.6917 },
  { latitude: 55.7558, longitude: 37.6173 },
  { latitude: 52.52, longitude: 13.405 },
  { latitude: 37.7749, longitude: -122.4194 },
  { latitude: 41.8781, longitude: -87.6298 },
  { latitude: 39.9042, longitude: 116.4074 },
  { latitude: 23.1291, longitude: 113.2644 },
  { latitude: 28.6139, longitude: 77.209 },
  { latitude: 19.076, longitude: 72.8777 }
]
